# Generated by Django 5.1.5 on 2025-02-01 15:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_level_comment_lft_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
