# Generated by Django 5.1.5 on 2025-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
