# Generated by Django 5.1.5 on 2025-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_advertisment_promoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
