# Generated by Django 5.1.5 on 2025-02-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
